namespace LINQSamples
{
  public partial class ProductRepository
  {
    #region GetAll Method
    public static List<Product> GetAll()
    {
      return new List<Product>
      {
        new Product {
          ProductID = 680,
          Name = "HL Road Frame - Black, 58",
          Color = "Purple",
          Cost = 1059.31M,
          ListPrice = 1431.50M,
          Size = "58",
        },
        new Product {
          ProductID = 706,
          Name = "HL Road Frame - Red, 58",
          Color = "Red",
          Cost = 1059.31M,
          ListPrice = 1431.50M,
          Size = "58",
        },
        new Product {
          ProductID = 707,
          Name = "Sport-100 Helmet, Red",
          Color = "Purple",
          Cost = 13.08M,
          ListPrice = 34.99M,
          Size = null,
        },
        new Product {
          ProductID = 708,
          Name = "Sport-100 Helmet, Black",
          Color = "Black",
          Cost = 14.09M,
          ListPrice = 35.99M,
          Size = null,
        },
        new Product {
          ProductID = 709,
          Name = "Mountain Bike Socks, M",
          Color = "Blue",
          Cost = 3.40M,
          ListPrice = 9.50M,
          Size = "M",
        },
        new Product {
          ProductID = 710,
          Name = "Mountain Bike Socks, L",
          Color = "White",
          Cost = 3.40M,
          ListPrice = 9.50M,
          Size = "L",
        },
        new Product {
          ProductID = 711,
          Name = "Sport-100 Helmet, Blue",
          Color = "Blue",
          Cost = 15.09M,
          ListPrice = 36.99M,
          Size = null,
        },
        new Product {
          ProductID = 712,
          Name = "AWC Logo Cap",
          Color = "Multi",
          Cost = 6.92M,
          ListPrice = 8.99M,
          Size = "",
        },
        new Product {
          ProductID = 713,
          Name = "Long-Sleeve Logo Jersey, S",
          Color = "Multi",
          Cost = 38.49M,
          ListPrice = 49.99M,
          Size = "S",
        },
        new Product {
          ProductID = 714,
          Name = "Long-Sleeve Logo Jersey, M",
          Color = "Multi",
          Cost = 38.49M,
          ListPrice = 49.99M,
          Size = "M",
        },
        new Product {
          ProductID = 715,
          Name = "Long-Sleeve Logo Jersey, L",
          Color = "Multi",
          Cost = 38.49M,
          ListPrice = 49.99M,
          Size = "L",
        },
        new Product {
          ProductID = 716,
          Name = "Long-Sleeve Logo Jersey, XL",
          Color = "Multi",
          Cost = 38.49M,
          ListPrice = 49.99M,
          Size = "XL",
        },
        new Product {
          ProductID = 717,
          Name = "HL Road Frame - Red, 62",
          Color = "Red",
          Cost = 868.63M,
          ListPrice = 1431.50M,
          Size = "62",
        },
        new Product {
          ProductID = 718,
          Name = "HL Road Frame - Red, 44",
          Color = "Red",
          Cost = 858.63M,
          ListPrice = 1431.50M,
          Size = "44",
        },
        new Product {
          ProductID = 719,
          Name = "HL Road Frame - Red, 48",
          Color = "Red",
          Cost = 868.63M,
          ListPrice = 1531.50M,
          Size = "48",
        },
        new Product {
          ProductID = 720,
          Name = "HL Road Frame - Red, 52",
          Color = "Red",
          Cost = 878.63M,
          ListPrice = 1631.50M,
          Size = "52",
        },
        new Product {
          ProductID = 721,
          Name = "HL Road Frame - Red, 56",
          Color = "Red",
          Cost = 888.63M,
          ListPrice = 1831.50M,
          Size = "56",
        },
        new Product {
          ProductID = 722,
          Name = "LL Road Frame - Black, 58",
          Color = "Black",
          Cost = 204.63M,
          ListPrice = 337.22M,
          Size = "58",
        },
        new Product {
          ProductID = 723,
          Name = "LL Road Frame - Black, 60",
          Color = "Black",
          Cost = 214.63M,
          ListPrice = 347.22M,
          Size = "60",
        },
        new Product {
          ProductID = 724,
          Name = "LL Road Frame - Black, 62",
          Color = "Black",
          Cost = 224.63M,
          ListPrice = 357.22M,
          Size = "62",
        },
        new Product {
          ProductID = 725,
          Name = "LL Road Frame - Red, 44",
          Color = "Red",
          Cost = 187.16M,
          ListPrice = 337.22M,
          Size = "44",
        },
        new Product {
          ProductID = 726,
          Name = "LL Road Frame - Red, 48",
          Color = "Red",
          Cost = 197.16M,
          ListPrice = 347.22M,
          Size = "48",
        },
        new Product {
          ProductID = 727,
          Name = "LL Road Frame - Red, 52",
          Color = "Red",
          Cost = 187.16M,
          ListPrice = 337.22M,
          Size = "52",
        },
        new Product {
          ProductID = 728,
          Name = "LL Road Frame - Red, 58",
          Color = "Red",
          Cost = 187.16M,
          ListPrice = 337.22M,
          Size = "58",
        },
        new Product {
          ProductID = 729,
          Name = "LL Road Frame - Red, 60",
          Color = "Red",
          Cost = 187.16M,
          ListPrice = 337.22M,
          Size = "60",
        },
        new Product {
          ProductID = 730,
          Name = "LL Road Frame - Red, 62",
          Color = "Red",
          Cost = 187.16M,
          ListPrice = 337.22M,
          Size = "62",
        },
        new Product {
          ProductID = 731,
          Name = "ML Road Frame - Red, 44",
          Color = "Red",
          Cost = 352.14M,
          ListPrice = 594.83M,
          Size = "44",
        },
        new Product {
          ProductID = 732,
          Name = "ML Road Frame - Red, 48",
          Color = "Red",
          Cost = 352.14M,
          ListPrice = 594.83M,
          Size = "48",
        },
        new Product {
          ProductID = 733,
          Name = "ML Road Frame - Red, 52",
          Color = "Red",
          Cost = 352.14M,
          ListPrice = 594.83M,
          Size = "52",
        },
        new Product {
          ProductID = 734,
          Name = "ML Road Frame - Red, 58",
          Color = "Red",
          Cost = 352.14M,
          ListPrice = 594.83M,
          Size = "58",
        },
        new Product {
          ProductID = 735,
          Name = "ML Road Frame - Red, 60",
          Color = "Red",
          Cost = 352.14M,
          ListPrice = 594.83M,
          Size = "60",
        },
        new Product {
          ProductID = 736,
          Name = "LL Road Frame - Black, 44",
          Color = "Black",
          Cost = 204.63M,
          ListPrice = 337.22M,
          Size = "44",
        },
        new Product {
          ProductID = 737,
          Name = "LL Road Frame - Black, 48",
          Color = "Black",
          Cost = 204.63M,
          ListPrice = 337.22M,
          Size = "48",
        },
        new Product {
          ProductID = 738,
          Name = "LL Road Frame - Black, 52",
          Color = "Black",
          Cost = 204.63M,
          ListPrice = 337.22M,
          Size = "52",
        },
        new Product {
          ProductID = 739,
          Name = "HL Mountain Frame - Silver, 42",
          Color = "Silver",
          Cost = 747.20M,
          ListPrice = 1364.50M,
          Size = "42",
        },
        new Product {
          ProductID = 740,
          Name = "HL Mountain Frame - Silver, 44",
          Color = "Silver",
          Cost = 706.81M,
          ListPrice = 1364.50M,
          Size = "44",
        },
        new Product {
          ProductID = 741,
          Name = "HL Mountain Frame - Silver, 48",
          Color = "Silver",
          Cost = 706.81M,
          ListPrice = 1364.50M,
          Size = "48",
        },
        new Product {
          ProductID = 742,
          Name = "HL Mountain Frame - Silver, 46",
          Color = "Silver",
          Cost = 747.20M,
          ListPrice = 1364.50M,
          Size = "46",
        },
        new Product {
          ProductID = 743,
          Name = "HL Mountain Frame - Black, 42",
          Color = "Black",
          Cost = 739.04M,
          ListPrice = 1349.60M,
          Size = "42",
        },
        new Product {
          ProductID = 744,
          Name = "HL Mountain Frame - Black, 44",
          Color = "Black",
          Cost = 699.09M,
          ListPrice = 1349.60M,
          Size = "44",
        }
      };
    }
    #endregion
  }
}